// <auto-generated />
using System;
using HostingFirmasıProje.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HostingFirmasıProje.Migrations
{
    [DbContext(typeof(HostingDbContext))]
    partial class HostingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HostingFirmasıProje.Models.Bayi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BayiAdi")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Bayiler");
                });

            modelBuilder.Entity("HostingFirmasıProje.Models.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BayiId");

                    b.Property<string>("MusteriAdi")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("BayiId");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("HostingFirmasıProje.Models.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BayiAdi")
                        .IsRequired();

                    b.Property<string>("DomainAdi")
                        .IsRequired();

                    b.Property<DateTime>("DomainBasTarihi");

                    b.Property<DateTime?>("DomainBitisTarihi")
                        .IsRequired();

                    b.Property<DateTime>("HostingBasTarihi");

                    b.Property<DateTime?>("HostingBitisTarihi")
                        .IsRequired();

                    b.Property<int?>("Kalan");

                    b.Property<int>("MusteriId");

                    b.Property<string>("PanelFtpBilgi");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.ToTable("Urunler");
                });

            modelBuilder.Entity("HostingFirmasıProje.Models.Musteri", b =>
                {
                    b.HasOne("HostingFirmasıProje.Models.Bayi", "Bayi")
                        .WithMany("Musteriler")
                        .HasForeignKey("BayiId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HostingFirmasıProje.Models.Urun", b =>
                {
                    b.HasOne("HostingFirmasıProje.Models.Musteri", "Musteri")
                        .WithMany("Urunler")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
